// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "sidebar":{
        "dashboard":"Dashboard",
        "users":"Users",
        "projects":"Projects",
        "allProjects":"All Projects",
        "createProject":"Create Project",
        "quickCreate":"Quick Create",
        "inbox":"Inbox"
    },
    "common":{
        "backToHome":"Back to home",
        "backToPrevious":"Back to previous",
        "tryAgain":"Try Again",
        "someThingWentWrong":"Something Went wrong!",
        "success":"Operation completed successfully",
        "error":"Error",
        "unauthorized":"Unauthorized access",
        "submit":"Submit",
        "noAccount":"Don't have an account?",
        "haveAccount":"Have an account?",
        "signUp":"Sign up",
        "login":"Login",
        "verifyAccount":"Verify Account",
        "noCode":"No code",
        "sendingCode":"Sending code",
        "resendCode":"Resend code",
        "saveChanges":"Save Changes",
        "chooseImage":"Choose Image",
        "uploadMessage":"Recommended: Square image, max 5MB",
        "avatarUploaded":"Avatar uploaded successfully",
        "uploadAvatar":"Upload avatar",
        "fileUploadError":"Failed to upload avatar",
        "accountStatus":"Account Status",
        "verified":"Verified",
        "unverified":"Unverified",
        "active":"Active",
        "inactive":"Inactive",
        "email":"Email",
        "phone":"Phone",
        "roles":{
            "admin":"Admin",
            "super_admin":"Super Admin",
            "user":"User"
        },
        "columns":{
            "firstName":"First Name",
            "lastName":"Last Name",
            "email":"Email",
            "phone":"Phone",
            "role":"Role",
            "createdAt":"Created At"
        },
        "loading":"Loading",
        "loadingDescription":"Please wait while we load the data",
        "page":"Page",
        "of":"of",
        "pages":"pages",
        "rowsPerPage":"Rows per page",
        "goToFirstPage":"Go to first page",
        "goToPreviousPage":"Go to previous page",
        "goToNextPage":"Go to next page",
        "goToLastPage":"Go to last page",   
        "searchPlaceholder":"Search here.",
        "createUser":"Create User",
        "editUser":"Edit User",
        "deleteUser":"Delete User",
        "filters":"Filters",
        "clear":"Clear",
        "filtersTitle":"Filters",
        "filtersDescription":"Filters the data in the table.",
        "resetFilters":"Reset Filters",
        "applyFilters":"Apply Filters",
        "all":"All",
        "selectRole":"Select Role",
        "openMenu":"Open Menu",
        "view":"View",
        "edit":"Edit",
        "delete":"Delete",
        "actions":"Actions",
        "create":"Create",
        "cancel":"Cancel"
    },
    "auth":{
        "title":"Flexify",
        "description":"Join the future of work with Flexify.",
        "login":{
            "title":"Login",
            "description":"Login to your Flexify account",
            "emailLabel":"Email",
            "passwordLabel":"Password",
            "emailValidation":"Invalid email address",
            "passwordValidation":"Password must be at least 8 characters",
            "emailPlaceholder":"email",
            "passwordPlaceholder":"password",
            "forgetPassword":"Forget password?",
            "metadata":{
                "title":"Login",
                "description":"Login to your Flexify account"
            },
            "message":{
                "success":"Login successful",
                "error":"Login failed"
            }
        },
        "register":{
            "title":"Register",
            "description":"Register a new account",
            "emailLabel":"Email",
            "emailValidation":"Invalid email address",
            "emailPlaceholder":"email",
            "passwordLabel":"Password",
            "passwordValidation":"Password must be at least 8 characters",
            "passwordPlaceholder":"password",
            "firstNameLabel":"First Name",
            "firstNamePlaceholder":"First Name",
            "firstNameValidation":"First name must be at most 20 characters",
            "lastNameLabel":"Last Name",
            "lastNamePlaceholder":"Last Name",
            "lastNameValidation":"Last name must be at most 20 characters",
            "phoneLabel":"Phone",
            "phoneValidation":"Phone must be at least 10 digits",
            "phonePlaceholder":"Phone Number",
            "metadata":{
                "title":"Register",
                "description":"Register a new account"
            },
            "message":{
                "success":"Account registered successfully",
                "error":"Account registration failed"
            }
        },
        "verifyAccount":{
            "title":"Verify Account",
            "description":"Verify your account",
            "otpValidation":"OTP must be 6 digits",
            "emailNotAvailable":"Email not available. Please register again.",
            "metadata":{
                "title":"Verify Account",
                "description":"Verify your account"
            },
            "message":{
                "success":"Account verified successfully",
                "error":"Account verification failed"
            }
        },
        "resendVerification":{
            "message":{
                "success":"Verification code sent successfully",
                "error":"Failed to send verification code"
            }
        },
        "forgetPassword":{
            "title":"Forget Password",
            "description":"You will receive an email with a link to reset your password",
            "emailLabel":"Email",
            "emailValidation":"Invalid email address",
            "emailPlaceholder":"email",
            "metadata":{
                "title":"Forget Password",
                "description":"Forget your password"
            },
            "message":{
                "success":"Password reset link sent successfully",
                "error":"Failed to send password reset link"
            }
        },
        "resetPassword":{
            "title":"Reset Password",
            "description":"Reset your password",
            "passwordLabel":"Password",
            "passwordValidation":"Password must be at least 8 characters",
            "passwordPlaceholder":"password",
            "tokenValidation":"Token is required",
            "metadata":{
                "title":"Reset Password",
                "description":"Reset your password"
            },
            "message":{
                "success":"Password reset successfully",
                "error":"Failed to reset password"
            }
        },
        "changePassword":{
            "title":"Change Password",
            "description":"Change your password",
            "currentPasswordLabel":"Current Password",
            "currentPasswordPlaceholder":"Current Password",
            "currentPasswordValidation":"Current password must be at least 8 characters",
            "newPasswordLabel":"New Password",
            "newPasswordPlaceholder":"New Password",
            "newPasswordValidation":"New password must be at least 8 characters",
            "message":{
                "success":"Password changed successfully",
                "error":"Failed to change password"
            }
        },
        "logout":{
            "title":"Logout",
            "description":"Logout from your account",
            "metadata":{
                "title":"Logout",
                "description":"Logout from your account"
            },
            "message":{
                "success":"Logged out successfully",
                "error":"Failed to logout"
            }
        }
    },
    "dashboard":{
        "profile":{
            "title":"Profile",
            "description":"You can manage your profile here.",
            "firstNameLabel":"First Name",
            "firstNamePlaceholder":"First Name",
            "firstNameValidation":"First name must be at most 20 characters",
            "lastNameLabel":"Last Name",
            "lastNamePlaceholder":"Last Name",
            "lastNameValidation":"Last name must be at most 20 characters",
            "emailLabel":"Email",
            "emailPlaceholder":"Email",
            "emailValidation":"Invalid email address",
            "phoneLabel":"Phone",
            "phonePlaceholder":"Phone Number",
            "phoneValidation":"Phone must be at least 10 digits",
            "currentPasswordLabel":"Current Password",
            "currentPasswordPlaceholder":"Current Password",
            "currentPasswordValidation":"Current password must be at least 8 characters",
            "newPasswordLabel":"New Password",
            "newPasswordPlaceholder":"New Password",
            "newPasswordValidation":"New password must be at least 8 characters",
            "confirmPasswordLabel":"Confirm Password",
            "confirmPasswordPlaceholder":"Confirm Password",
            "confirmPasswordValidation":"Confirm password must be at least 8 characters",
            "tabs":{
                "overview":{
                    "title":"Profile",
                    "description":"You can view your personal information here."
                },
                "editProfile":{
                    "title":"Edit Profile",
                    "description":"You can update your personal information here."
                },
                "changePassword":{
                    "title":"Change Password",
                    "description":"You can change your password here."
                }
            },
            "metadata":{
                "title":"Profile",
                "description":"Profile"
            }
        },
        "users":{
            "title":"Users",
            "description":"You can manage users here.",
            "createUser":{
                "title":"Create User",
                "description":"You can create a new user here.",
                "emailLabel":"Email",
                "emailPlaceholder":"Email",
                "emailValidation":"Invalid email address",
                "passwordLabel":"Password",
                "passwordValidation":"Password must be at least 8 characters",
                "passwordPlaceholder":"Password",
                "firstNameLabel":"First Name",
                "firstNamePlaceholder":"First Name",
                "firstNameValidation":"First name must be at most 20 characters",
                "lastNameLabel":"Last Name",
                "lastNamePlaceholder":"Last Name",
                "lastNameValidation":"Last name must be at most 20 characters",
                "phoneLabel":"Phone",
                "phonePlaceholder":"Phone Number",
                "phoneValidation":"Phone must be at least 10 digits"
            },
            "editUser":{
                "title":"Edit User",
                "description":"You can edit the user here.",
                "emailLabel":"Email",
                "emailPlaceholder":"Email",
                "emailValidation":"Invalid email address",
                "passwordLabel":"Password",
                "passwordValidation":"Password must be at least 8 characters",
                "passwordPlaceholder":"Password",
                "firstNameLabel":"First Name",
                "firstNamePlaceholder":"First Name",
                "firstNameValidation":"First name must be at most 20 characters",
                "lastNameLabel":"Last Name",
                "lastNamePlaceholder":"Last Name",
                "lastNameValidation":"Last name must be at most 20 characters",
                "phoneLabel":"Phone",
                "phonePlaceholder":"Phone Number",
                "phoneValidation":"Phone must be at least 10 digits"
            },
            "deleteUser":{
                "title":"Delete User",
                "description":"You can delete the user here."
            },
            "message":{
                "createSuccess":"User created successfully",
                "createError":"Failed to create user",
                "updateSuccess":"User updated successfully",
                "updateError":"Failed to update user",
                "deleteSuccess":"User deleted successfully",
                "deleteError":"Failed to delete user",
                "uploadSuccess":"Avatar uploaded successfully",
                "uploadError":"Failed to upload avatar"
            },
            "metadata":{
                "title":"Users",
                "description":"Users"
            },
            "detail":{
                "title":"User Details",
                "description":"View detailed information about the user",
                "lastLogin":"Last Login",
                "createdAt":"Created At",
                "updatedAt":"Updated At",
                "sections":{
                    "personalInfo":"Personal Information",
                    "personalInfoDescription":"Basic information about the user",
                    "accountInfo":"Account Information",
                    "accountInfoDescription":"Account status and settings"
                },
                "metadata":{
                    "title":"User Details - {id}",
                    "description":"View detailed information about the user"
                }
            }
        },
        "projects":{
            "title":"Projects",
            "description":"Manage your portfolio projects",
            "createButton":"Create Project",
            "metadata":{
                "title":"Projects - Portfolio Management",
                "description":"Manage and organize your portfolio projects. View, create, edit, and delete projects with ease.",
                "keywords":"projects, portfolio, management, create project, edit project, project management"
            },
            "create":{
                "metadata":{
                    "title":"Create New Project - Portfolio",
                    "description":"Create a new project for your portfolio. Add details, images, technologies, and links.",
                    "keywords":"create project, new project, portfolio, add project, project creation"
                }
            },
            "edit":{
                "metadata":{
                    "title":"Edit Project - Portfolio",
                    "description":"Edit project details, translations, images, technologies, and links.",
                    "keywords":"edit project, update project, modify project, project editing"
                },
                "loading":{
                    "title":"Loading Project",
                    "description":"Please wait while we load the project details..."
                },
                "error":{
                    "title":"Project Not Found",
                    "description":"The project you're looking for doesn't exist or has been deleted."
                }
            },
            "images":{
                "metadata":{
                    "title":"Manage Project Images - Portfolio",
                    "description":"Upload, reorder, and manage images for your project gallery.",
                    "keywords":"project images, image gallery, upload images, manage images, project photos"
                },
                "loading":{
                    "title":"Loading Project Images",
                    "description":"Please wait while we load the project images..."
                },
                "error":{
                    "title":"Project Not Found",
                    "description":"The project you're looking for doesn't exist or has been deleted."
                }
            },
            "columns":{
                "thumbnail":"Thumbnail",
                "title":"Title",
                "slug":"Slug",
                "type":"Type",
                "status":"Status",
                "featured":"Featured",
                "stats":"Stats",
                "createdAt":"Created At"
            },
            "status":{
                "draft":"Draft",
                "in_progress":"In Progress",
                "published":"Published",
                "archived":"Archived"
            },
            "type":{
                "personal":"Personal",
                "client":"Client",
                "open_source":"Open Source"
            },
            "toolbar":{
                "searchPlaceholder":"Search projects...",
                "statusFilter":"Status",
                "typeFilter":"Type",
                "allStatuses":"All Statuses",
                "allTypes":"All Types",
                "reset":"Reset"
            },
            "actions":{
                "openMenu":"Open menu",
                "actions":"Actions",
                "view":"View",
                "edit":"Edit",
                "delete":"Delete"
            },
            "deleteModal":{
                "title":"Delete Project",
                "description":"Are you sure you want to delete \"{title}\"? This action cannot be undone.",
                "cancel":"Cancel",
                "delete":"Delete",
                "deleting":"Deleting..."
            },
            "form":{
                "tabs":{
                    "basic":"Basic Info",
                    "translations":"Translations",
                    "relations":"Relations",
                    "links":"Links",
                    "settings":"Settings"
                },
                "basicInfo":{
                    "title":"Basic Information",
                    "description":"Enter the basic details of your project"
                },
                "slug":{
                    "label":"Slug",
                    "placeholder":"my-awesome-project",
                    "description":"URL-friendly identifier (lowercase, hyphens only)"
                },
                "thumbnail":{
                    "label":"Thumbnail Image",
                    "description":"Upload a thumbnail image (max 5MB)",
                    "uploadTitle":"Upload Thumbnail",
                    "uploadDescription":"Click or drag image to upload (max 5MB)"
                },
                "images":{
                    "title":"Project Images",
                    "existing":"Existing Images",
                    "addNew":"Add New Images",
                    "uploadTitle":"Upload Images",
                    "uploadDescription":"Click or drag images to upload (max 10MB each)",
                    "selected":"Selected Images",
                    "uploading":"Uploading...",
                    "uploadAll":"Upload All",
                    "dragToReorder":"Drag images to reorder them",
                    "editAltText":"Edit Image Alt Text",
                    "altTextDescription":"Add descriptive text for accessibility and SEO",
                    "altTextLabel":"Alt Text",
                    "altTextPlaceholder":"Describe this image...",
                    "cancel":"Cancel",
                    "save":"Save",
                    "uploadHint":"Click or drag images to upload (max 10MB each)"
                },
                "startDate":{
                    "label":"Start Date"
                },
                "endDate":{
                    "label":"End Date"
                },
                "translations":{
                    "english":"English Translation",
                    "arabic":"Arabic Translation"
                },
                "title":{
                    "label":"Title",
                    "placeholder":"Enter project title"
                },
                "shortDescription":{
                    "label":"Short Description",
                    "placeholder":"Brief description (max 500 characters)"
                },
                "description":{
                    "label":"Description",
                    "placeholder":"Detailed description"
                },
                "content":{
                    "label":"Content",
                    "placeholder":"Full project content (supports markdown)"
                },
                "technologies":{
                    "title":"Technologies",
                    "description":"Select technologies used in this project"
                },
                "categories":{
                    "title":"Categories",
                    "description":"Select project categories"
                },
                "links":{
                    "title":"Project Links",
                    "description":"Add links to your project (GitHub, Demo, Documentation, etc.)",
                    "existingLinks":"Existing Links",
                    "addNewLink":"Add New Link",
                    "addNewLinkDescription":"Add external links related to your project",
                    "linkType":"Link Type",
                    "selectLinkType":"Select link type",
                    "url":"URL",
                    "urlPlaceholder":"https://example.com",
                    "label":"Label",
                    "labelPlaceholder":"e.g., Live Demo, Source Code",
                    "optional":"Optional",
                    "addLink":"Add Link"
                },
                "settings":{
                    "title":"Project Settings",
                    "description":"Configure project visibility and metadata"
                },
                "projectType":{
                    "label":"Project Type",
                    "placeholder":"Select type",
                    "personal":"Personal Project",
                    "client":"Client Project",
                    "openSource":"Open Source"
                },
                "status":{
                    "label":"Status",
                    "placeholder":"Select status",
                    "draft":"Draft",
                    "inProgress":"In Progress",
                    "published":"Published",
                    "archived":"Archived"
                },
                "orderIndex":{
                    "label":"Order Index",
                    "description":"Lower numbers appear first"
                },
                "isFeatured":{
                    "label":"Featured Project",
                    "description":"Display this project prominently"
                },
                "cancel":"Cancel",
                "create":"Create Project",
                "update":"Update Project"
            },
            "detail":{
                "metadata":{
                    "title":"Project Details - Portfolio",
                    "description":"View detailed information about the project including images, technologies, and links.",
                    "keywords":"project details, project view, portfolio project, project information"
                },
                "loading":{
                    "title":"Loading Project Details",
                    "description":"Please wait while we load the project information..."
                },
                "error":{
                    "title":"Project Not Found",
                    "description":"The project you're looking for doesn't exist or has been deleted."
                },
                "manageImages":"Manage Images",
                "edit":"Edit Project",
                "createdAt":"Created",
                "views":"Views",
                "likes":"Likes",
                "shares":"Shares",
                "comments":"Comments",
                "englishContent":"English Content",
                "arabicContent":"Arabic Content",
                "shortDescription":"Short Description",
                "description":"Description",
                "content":"Content",
                "gallery":"Image Gallery",
                "projectInfo":"Project Information",
                "slug":"Slug",
                "status":"Status",
                "type":"Type",
                "featured":"Featured",
                "startDate":"Start Date",
                "endDate":"End Date",
                "technologies":"Technologies",
                "categories":"Categories",
                "links":"Project Links"
            },
            "message":{
                "createSuccess":"Project created successfully",
                "createError":"Failed to create project",
                "updateSuccess":"Project updated successfully",
                "updateError":"Failed to update project",
                "deleteSuccess":"Project deleted successfully",
                "deleteError":"Failed to delete project",
                "thumbnailUploadSuccess":"Thumbnail uploaded successfully",
                "thumbnailUploadError":"Failed to upload thumbnail",
                "imageUploadSuccess":"Image uploaded successfully",
                "imageUploadError":"Failed to upload image",
                "imageDeleteSuccess":"Image deleted successfully",
                "imageDeleteError":"Failed to delete image",
                "likeAdded":"Project liked",
                "likeRemoved":"Like removed",
                "shareAdded":"Project shared",
                "shareRemoved":"Share removed",
                "interactionError":"Failed to update interaction",
                "commentCreateSuccess":"Comment added successfully",
                "commentCreateError":"Failed to add comment",
                "commentDeleteSuccess":"Comment deleted successfully",
                "commentDeleteError":"Failed to delete comment"
            }
        }
    },
    "portfolio": {
        "home": {
            "hero": {
                "badge": "Full Stack Developer",
                "title": "Full Stack Developer",
                "description": "Building modern web applications with **Next.js**, **NestJS**, **TypeScript**, **Prisma**, **MySQL**, and **Supabase**. Creating scalable solutions from frontend to backend.",
                "cta": "Get Started - It's free"
            },
            "statistics": {
                "title": "By The Numbers",
                "description": "A glimpse into my journey and achievements",
                "items": {
                    "years": {
                        "label": "Years of Experience"
                    },
                    "projects": {
                        "label": "Projects Completed"
                    },
                    "technologies": {
                        "label": "Technologies Mastered"
                    },
                    "clients": {
                        "label": "Happy Clients"
                    }
                }
            },
            "about": {
                "title": "About Me",
                "description1": "I'm a passionate **Full Stack Developer** with a love for creating innovative web solutions. My journey in software development has been driven by curiosity and a commitment to building applications that make a difference.",
                "description2": "I specialize in modern web technologies, focusing on creating scalable, maintainable, and user-friendly applications. From **frontend interfaces** to **backend APIs**, I bring ideas to life with clean code and best practices.",
                "cta": "Learn More",
                "highlights": {
                    "code": {
                        "title": "Clean Code",
                        "description": "Writing maintainable and scalable code following best practices"
                    },
                    "rocket": {
                        "title": "Fast Delivery",
                        "description": "Efficient development process with quick turnaround times"
                    },
                    "heart": {
                        "title": "Passion Driven",
                        "description": "Genuine love for technology and continuous learning"
                    },
                    "target": {
                        "title": "Goal Oriented",
                        "description": "Focused on delivering solutions that meet business objectives"
                    }
                }
            },
            "services": {
                "title": "My Services",
                "description": "Comprehensive solutions for your digital needs",
                "seeMore": "See More",
                "seeLess": "See Less",
                "items": {
                    "web": {
                        "title": "Web Development",
                        "description": "Building responsive and modern web applications using the latest technologies"
                    },
                    "frontend": {
                        "title": "Frontend Development",
                        "description": "Creating beautiful and interactive user interfaces with React, Next.js, and TypeScript"
                    },
                    "backend": {
                        "title": "Backend Development",
                        "description": "Developing robust APIs and server-side solutions with NestJS and Node.js"
                    },
                    "cloud": {
                        "title": "Cloud Solutions",
                        "description": "Deploying and managing applications on cloud platforms like AWS, Azure, and Supabase"
                    },
                    "mobile": {
                        "title": "Mobile Development",
                        "description": "Building cross-platform mobile applications with React Native and Flutter"
                    },
                    "devops": {
                        "title": "DevOps & CI/CD",
                        "description": "Setting up automated deployment pipelines and infrastructure management",
                        "moreContent": "I help teams streamline their development workflow with modern DevOps practices:",
                        "features": [
                            "Continuous Integration and Deployment pipelines",
                            "Container orchestration with Docker and Kubernetes",
                            "Infrastructure as Code with Terraform and CloudFormation"
                        ]
                    }
                }
            },
            "testimonials": {
                "title": "What Clients Say",
                "description": "Hear from the people I've worked with"
            },
            "cta": {
                "title": "Ready to Start Your Project?",
                "description": "Let's work together to bring your ideas to life. Get in touch and let's discuss how I can help you achieve your goals.",
                "primaryButton": "Contact Me",
                "secondaryButton": "View Projects"
            },
            "featuredProjects": {
                "title": "Featured Projects",
                "description": "Explore some of my best work and creative solutions",
                "viewAll": "View All Projects"
            }
        },
        "projects": {
            "title": "My Projects",
            "description": "A collection of my work showcasing creativity, innovation, and technical expertise",
            "searchPlaceholder": "Search projects...",
            "filters": "Filters",
            "projectType": "Project Type",
            "category": "Category",
            "allTypes": "All Types",
            "allCategories": "All Categories",
            "personal": "Personal",
            "client": "Client",
            "openSource": "Open Source",
            "clearFilters": "Clear Filters",
            "activeFilters": "Active Filters",
            "search": "Search",
            "type": "Type",
            "showing": "Showing",
            "of": "of",
            "projects": "projects",
            "noProjects": "No projects found. Try adjusting your filters.",
            "previous": "Previous",
            "next": "Next"
        },
        "projectDetails": {
            "notFound": "Project not found",
            "backToProjects": "Back to Projects",
            "featured": "Featured",
            "share": "Share",
            "description": "Description",
            "gallery": "Gallery",
            "technologies": "Technologies",
            "links": "Links",
            "info": "Project Information",
            "status": "Status",
            "startDate": "Start Date",
            "endDate": "End Date",
            "views": "Views",
            "likes": "Likes",
            "loginRequired": "Please login to like this project",
            "comments": {
                "title": "Comments",
                "placeholder": "Write a comment...",
                "submit": "Post Comment",
                "submitting": "Posting...",
                "loginRequired": "Please login to comment",
                "login": "Login",
                "noComments": "No comments yet. Be the first to comment!"
            }
        },
        "contact": {
            "title": "Get In Touch",
            "description": "Have a project in mind? I'd love to hear from you. Send me a message and I'll respond as soon as possible.",
            "info": {
                "email": {
                    "label": "Email",
                    "value": "your.email@example.com"
                },
                "phone": {
                    "label": "Phone",
                    "value": "+1 (555) 123-4567"
                },
                "location": {
                    "label": "Location",
                    "value": "Your City, Country"
                }
            },
            "form": {
                "name": {
                    "label": "Name",
                    "placeholder": "Your name",
                    "validation": "Name must be at least 2 characters"
                },
                "email": {
                    "label": "Email",
                    "placeholder": "your.email@example.com",
                    "validation": "Please enter a valid email address"
                },
                "subject": {
                    "label": "Subject",
                    "placeholder": "What is this about?",
                    "validation": "Subject must be at least 3 characters"
                },
                "message": {
                    "label": "Message",
                    "placeholder": "Tell me about your project...",
                    "validation": "Message must be at least 10 characters"
                },
                "submit": "Send Message",
                "submitting": "Sending..."
            }
        },
        "footer": {
            "description": "Full Stack Developer building modern web applications with cutting-edge technologies.",
            "quickLinks": "Quick Links",
            "links": {
                "home": "Home",
                "about": "About",
                "projects": "Projects",
                "contact": "Contact"
            },
            "resources": {
                "title": "Resources",
                "blog": "Blog",
                "other": "Other"
            },
            "contact": {
                "title": "Contact",
                "email": "your.email@example.com",
                "phone": "+1 (555) 123-4567",
                "location": "Your City, Country"
            },
            "copyright": "All rights reserved.",
            "rights": "Built with Next.js, NestJS & TypeScript"
        }
    }
};
export default messages;