// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "common":{
        "backToHome":"Back to home",
        "backToPrevious":"Back to previous",
        "tryAgain":"Try Again",
        "someThingWentWrong":"Something Went wrong!",
        "success":"Operation completed successfully",
        "error":"Error",
        "unauthorized":"Unauthorized access",
        "submit":"Submit",
        "noAccount":"Don't have an account?",
        "haveAccount":"Have an account?",
        "signUp":"Sign up",
        "login":"Login",
        "verifyAccount":"Verify Account",
        "noCode":"No code",
        "sendingCode":"Sending code",
        "resendCode":"Resend code",
        "saveChanges":"Save Changes",
        "chooseImage":"Choose Image",
        "uploadMessage":"Recommended: Square image, max 5MB",
        "avatarUploaded":"Avatar uploaded successfully",
        "uploadAvatar":"Upload avatar",
        "fileUploadError":"Failed to upload avatar",
        "accountStatus":"Account Status",
        "verified":"Verified",
        "unverified":"Unverified",
        "active":"Active",
        "inactive":"Inactive",
        "email":"Email",
        "phone":"Phone",
        "roles":{
            "admin":"Admin",
            "super_admin":"Super Admin",
            "user":"User"
        },
        "columns":{
            "firstName":"First Name",
            "lastName":"Last Name",
            "email":"Email",
            "phone":"Phone",
            "role":"Role",
            "createdAt":"Created At"
        },
        "loading":"Loading",
        "loadingDescription":"Please wait while we load the data",
        "page":"Page",
        "of":"of",
        "pages":"pages",
        "rowsPerPage":"Rows per page",
        "goToFirstPage":"Go to first page",
        "goToPreviousPage":"Go to previous page",
        "goToNextPage":"Go to next page",
        "goToLastPage":"Go to last page",   
        "searchPlaceholder":"Search here.",
        "createUser":"Create User",
        "editUser":"Edit User",
        "deleteUser":"Delete User",
        "filters":"Filters",
        "clear":"Clear",
        "filtersTitle":"Filters",
        "filtersDescription":"Filters the data in the table.",
        "resetFilters":"Reset Filters",
        "applyFilters":"Apply Filters",
        "all":"All",
        "selectRole":"Select Role",
        "openMenu":"Open Menu",
        "view":"View",
        "edit":"Edit",
        "delete":"Delete",
        "actions":"Actions",
        "create":"Create",
        "cancel":"Cancel"
    },
    "auth":{
        "title":"Flexify",
        "description":"Join the future of work with Flexify.",
        "login":{
            "title":"Login",
            "description":"Login to your Flexify account",
            "emailLabel":"Email",
            "passwordLabel":"Password",
            "emailValidation":"Invalid email address",
            "passwordValidation":"Password must be at least 8 characters",
            "emailPlaceholder":"email",
            "passwordPlaceholder":"password",
            "forgetPassword":"Forget password?",
            "metadata":{
                "title":"Login",
                "description":"Login to your Flexify account"
            },
            "message":{
                "success":"Login successful",
                "error":"Login failed"
            }
        },
        "register":{
            "title":"Register",
            "description":"Register a new account",
            "emailLabel":"Email",
            "emailValidation":"Invalid email address",
            "emailPlaceholder":"email",
            "passwordLabel":"Password",
            "passwordValidation":"Password must be at least 8 characters",
            "passwordPlaceholder":"password",
            "firstNameLabel":"First Name",
            "firstNamePlaceholder":"First Name",
            "firstNameValidation":"First name must be at most 20 characters",
            "lastNameLabel":"Last Name",
            "lastNamePlaceholder":"Last Name",
            "lastNameValidation":"Last name must be at most 20 characters",
            "phoneLabel":"Phone",
            "phoneValidation":"Phone must be at least 10 digits",
            "phonePlaceholder":"Phone Number",
            "metadata":{
                "title":"Register",
                "description":"Register a new account"
            },
            "message":{
                "success":"Account registered successfully",
                "error":"Account registration failed"
            }
        },
        "verifyAccount":{
            "title":"Verify Account",
            "description":"Verify your account",
            "otpValidation":"OTP must be 6 digits",
            "emailNotAvailable":"Email not available. Please register again.",
            "metadata":{
                "title":"Verify Account",
                "description":"Verify your account"
            },
            "message":{
                "success":"Account verified successfully",
                "error":"Account verification failed"
            }
        },
        "resendVerification":{
            "message":{
                "success":"Verification code sent successfully",
                "error":"Failed to send verification code"
            }
        },
        "forgetPassword":{
            "title":"Forget Password",
            "description":"You will receive an email with a link to reset your password",
            "emailLabel":"Email",
            "emailValidation":"Invalid email address",
            "emailPlaceholder":"email",
            "metadata":{
                "title":"Forget Password",
                "description":"Forget your password"
            },
            "message":{
                "success":"Password reset link sent successfully",
                "error":"Failed to send password reset link"
            }
        },
        "resetPassword":{
            "title":"Reset Password",
            "description":"Reset your password",
            "passwordLabel":"Password",
            "passwordValidation":"Password must be at least 8 characters",
            "passwordPlaceholder":"password",
            "tokenValidation":"Token is required",
            "metadata":{
                "title":"Reset Password",
                "description":"Reset your password"
            },
            "message":{
                "success":"Password reset successfully",
                "error":"Failed to reset password"
            }
        },
        "changePassword":{
            "title":"Change Password",
            "description":"Change your password",
            "currentPasswordLabel":"Current Password",
            "currentPasswordPlaceholder":"Current Password",
            "currentPasswordValidation":"Current password must be at least 8 characters",
            "newPasswordLabel":"New Password",
            "newPasswordPlaceholder":"New Password",
            "newPasswordValidation":"New password must be at least 8 characters",
            "message":{
                "success":"Password changed successfully",
                "error":"Failed to change password"
            }
        },
        "logout":{
            "title":"Logout",
            "description":"Logout from your account",
            "metadata":{
                "title":"Logout",
                "description":"Logout from your account"
            },
            "message":{
                "success":"Logged out successfully",
                "error":"Failed to logout"
            }
        }
    },
    "dashboard":{
        "profile":{
            "title":"Profile",
            "description":"You can manage your profile here.",
            "firstNameLabel":"First Name",
            "firstNamePlaceholder":"First Name",
            "firstNameValidation":"First name must be at most 20 characters",
            "lastNameLabel":"Last Name",
            "lastNamePlaceholder":"Last Name",
            "lastNameValidation":"Last name must be at most 20 characters",
            "emailLabel":"Email",
            "emailPlaceholder":"Email",
            "emailValidation":"Invalid email address",
            "phoneLabel":"Phone",
            "phonePlaceholder":"Phone Number",
            "phoneValidation":"Phone must be at least 10 digits",
            "currentPasswordLabel":"Current Password",
            "currentPasswordPlaceholder":"Current Password",
            "currentPasswordValidation":"Current password must be at least 8 characters",
            "newPasswordLabel":"New Password",
            "newPasswordPlaceholder":"New Password",
            "newPasswordValidation":"New password must be at least 8 characters",
            "confirmPasswordLabel":"Confirm Password",
            "confirmPasswordPlaceholder":"Confirm Password",
            "confirmPasswordValidation":"Confirm password must be at least 8 characters",
            "tabs":{
                "overview":{
                    "title":"Profile",
                    "description":"You can view your personal information here."
                },
                "editProfile":{
                    "title":"Edit Profile",
                    "description":"You can update your personal information here."
                },
                "changePassword":{
                    "title":"Change Password",
                    "description":"You can change your password here."
                }
            },
            "metadata":{
                "title":"Profile",
                "description":"Profile"
            }
        },
        "users":{
            "title":"Users",
            "description":"You can manage users here.",
            "createUser":{
                "title":"Create User",
                "description":"You can create a new user here.",
                "emailLabel":"Email",
                "emailPlaceholder":"Email",
                "emailValidation":"Invalid email address",
                "passwordLabel":"Password",
                "passwordValidation":"Password must be at least 8 characters",
                "passwordPlaceholder":"Password",
                "firstNameLabel":"First Name",
                "firstNamePlaceholder":"First Name",
                "firstNameValidation":"First name must be at most 20 characters",
                "lastNameLabel":"Last Name",
                "lastNamePlaceholder":"Last Name",
                "lastNameValidation":"Last name must be at most 20 characters",
                "phoneLabel":"Phone",
                "phonePlaceholder":"Phone Number",
                "phoneValidation":"Phone must be at least 10 digits"
            },
            "editUser":{
                "title":"Edit User",
                "description":"You can edit the user here.",
                "emailLabel":"Email",
                "emailPlaceholder":"Email",
                "emailValidation":"Invalid email address",
                "passwordLabel":"Password",
                "passwordValidation":"Password must be at least 8 characters",
                "passwordPlaceholder":"Password",
                "firstNameLabel":"First Name",
                "firstNamePlaceholder":"First Name",
                "firstNameValidation":"First name must be at most 20 characters",
                "lastNameLabel":"Last Name",
                "lastNamePlaceholder":"Last Name",
                "lastNameValidation":"Last name must be at most 20 characters",
                "phoneLabel":"Phone",
                "phonePlaceholder":"Phone Number",
                "phoneValidation":"Phone must be at least 10 digits"
            },
            "deleteUser":{
                "title":"Delete User",
                "description":"You can delete the user here."
            },
            "message":{
                "createSuccess":"User created successfully",
                "createError":"Failed to create user",
                "updateSuccess":"User updated successfully",
                "updateError":"Failed to update user",
                "deleteSuccess":"User deleted successfully",
                "deleteError":"Failed to delete user",
                "uploadSuccess":"Avatar uploaded successfully",
                "uploadError":"Failed to upload avatar"
            },
            "metadata":{
                "title":"Users",
                "description":"Users"
            },
            "detail":{
                "title":"User Details",
                "description":"View detailed information about the user",
                "lastLogin":"Last Login",
                "createdAt":"Created At",
                "updatedAt":"Updated At",
                "sections":{
                    "personalInfo":"Personal Information",
                    "personalInfoDescription":"Basic information about the user",
                    "accountInfo":"Account Information",
                    "accountInfoDescription":"Account status and settings"
                },
                "metadata":{
                    "title":"User Details - {id}",
                    "description":"View detailed information about the user"
                }
            }
        }
    }
};
export default messages;