// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "title":"Title",
    "common":{
        "backToHome":"Back to home",
        "backToPrevious":"Back to previous",
   
        "tryAgain":"Try Again",
        "someThingWentWrong":"Something Went wrong!"
    }
};
export default messages;